import binascii
import os

from pathlib import Path
from shutil import rmtree
from pdf_extractor import Extractor
from img2img_encoder import Encoder
from img2img_decoder import Decoder
from AES import AESCipher
from qr_generator import QR
from pdf_template import PdfTemplate
from text2img_encoder import TextEncoder
from text2img_decoder import TextDecoder
import cv2
import random
import fitz



while (1):

    print("[1] Encode")
    print("[2] Decode")
    print("[3] Exit")

    option = input("Choose one of the options above: ")

    if option == "1":

        path = str(Path.cwd()) + '/images/'

        path_coldplay_image = path + 'coldplay_image.png'
        path_coldplay_qr = path + 'coldplay_qr.png'

        #1. Read the content of a file we want to hide
        print("Encoding")

        file_name_to_hide = input("Introduce the file name which content you want to encode: ")
        with open(file_name_to_hide, 'r') as file:
            content = file.read()
        
        #2. Generate a random key
        random_key = os.urandom(16)
        random_key_str = binascii.hexlify(random_key).decode('utf-8')
        print("Random key:", random_key_str)

        #3. Encrypt the contents of the file with this random key
        AESCipher.init(random_key_str)
        ciphered_content = AESCipher.encrypt(content).decode()
        print("Ciphered content with key", ciphered_content)

        #4. Encrypt the random key with a key entered by the user.
        random_number = random.randint(0, 9999)
        number_with_format = "{:04d}".format(random_number)
        print("The verification PIN Code is: " + number_with_format)

        #5. Insert the encrypted key into a QR generated by us.
        qr_name_path = path + "qr_random_key_ciphered.png"
        QR.generate_qr(random_key_str, qr_name_path)

        #6. Insert the generated QR inside the QR that redirects to the Coldplay website.
        img_visible_path = path + 'coldplay_qr.png'
        img_hiden_path = qr_name_path 
        output_path = path + 'qr_coldplay_hidden.png'
        Encoder.hide_image(img_visible_path, img_hiden_path, output_path)
        print("Ocultado el QR")

        #7. Hide the file content in the main PDF image
        path_coldplay_image_hidden = path + 'coldplay_image_hidden.png'
        TextEncoder.ocultar_texto(ciphered_content, path_coldplay_image, path_coldplay_image_hidden)

        #8. Generamos el PDF con el QR que contiene el otro QR y la imagen donde vamos a ocultar el mensaje principal
        pdf_name = input("Introduce the PDF name to generate: ")
        path_coldplay_image_hidden = path + 'coldplay_image_hidden.png'
        path_qr_coldplay_hidden = path + 'qr_coldplay_hidden.png'
        PdfTemplate.create(pdf_name, path_coldplay_image_hidden, path_qr_coldplay_hidden, number_with_format)

        print("El contenido del archivo que has propocionado se ha ocultado en el PDF creado.")

        # Remove tmp files
        os.remove(path_coldplay_image_hidden)
        os.remove(path_qr_coldplay_hidden)
        os.remove(qr_name_path)

    elif option == "2":
        print("Decoding")

        #1. Leer el pdf que el usuario quiere decodificar
        pdf_name = input("Introduce the PDF file name to decode: ")

        user_key = input("Introduce the user PIN to decrypt the random key: ")
        doc = fitz.open(pdf_name)
        text = ""
        for page in doc:
            text+=page.get_text()

        text_array = text.split("\n")
        fecha = text_array[2]
        hora = text_array[4]
        lugar = text_array[6]
        precio = text_array[8]

        digits=""

        #print("Espacios en Fecha: " + str(fecha.count(" ")))
        digits+=str(fecha.count(" "))
        #print("Espacios en Hora: " + str(hora.count(" ")))
        digits+=str(hora.count(" "))
        #print("Espacios en Lugar: " + str(lugar.count(" ")))
        digits+=str(lugar.count(" "))
        #print("Espacios en Precio: " + str(precio.count(" ")))
        digits+=str(precio.count(" "))

        print(digits)
        if user_key!=digits:
            print("No coincide con el código de verificación. Introduce el codigo generado en el Encode")
        
        else:

            #2. Extract background image and QR
            Extractor.extractImages(pdf_name)

            tmp_path = "tmp/"
            image_tmp_path = tmp_path + "1.png"
            qr_tmp_path = tmp_path + "2.png"

            if not Extractor.check_qr(qr_tmp_path):
                image_tmp_path = tmp_path + "2.png"
                qr_tmp_path = tmp_path + "1.png"


            #3. Extraer del QR del PDF el QR con la clave cifrada
            qr_ciphered_path = tmp_path + "qr_random_key_ciphered.png"
            Decoder.extract_hidden_image(qr_tmp_path, qr_ciphered_path)

            #4. Leer ese QR extraido para obtener la clave aleatoria cifrada
            img = cv2.imread(qr_ciphered_path)
            det = cv2.QRCodeDetector()
            random_key_clear, pts, st_code = det.detectAndDecode(img)
            print("Random key hidden in QR: ", random_key_clear)


            #6. Extraer el texto escondido (cifrado) en la imagen 
            text_ciphered = TextDecoder.leer(image_tmp_path)
            

            #7. Descifrar el contenido de la imagen con la random_key
            AESCipher.init(random_key_clear)
            text_clear = AESCipher.decrypt(text_ciphered)
            print("The secret is:\n", text_clear)
            print("\n")
            rmtree("tmp")



    else:
        exit()











